# Remediation: Store passwords using reversible encryption setting on Windows
# CIS Benchmark: 1.1.7 (L1) Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
# Generated by CIS Script Generator

[CmdletBinding()]
param()

$VerboseOutput = $PSCmdlet.MyInvocation.BoundParameters.ContainsKey('Verbose')

# Import the required modules
$modulePath = Join-Path $PSScriptRoot "..\..\..\..\modules\ModuleIndex.psm1"
Import-Module $modulePath -Force -WarningAction SilentlyContinue

# Check admin rights and handle elevation
if (-not (Test-AdminRights)) {
    Invoke-Elevation
}

try {
    # Initialize result object
    $scriptResult = $null
    
    if ($VerboseOutput) {
        Write-SectionHeader -Title "Password Policy Remediation: Store Passwords Using Reversible Encryption"
    }
    
    # Check if this is a domain environment
    $isDomainMember = (Get-CimInstance -ClassName Win32_ComputerSystem).PartOfDomain
    
    # Display current status
    if ($VerboseOutput) {
        Write-Host ""
        Write-Host "CURRENT STATUS:" -ForegroundColor Cyan
        Write-Host "==============" -ForegroundColor Cyan
        Write-Host "Setting: Store passwords using reversible encryption" -ForegroundColor White
        Write-Host "Recommended: Disabled" -ForegroundColor White
        Write-Host ""
    }
    
    # Perform remediation based on environment
    if ($isDomainMember) {
        if ($VerboseOutput) {
            Write-StatusMessage -Message "Domain environment detected - remediation requires domain policy changes" -Type Warning
            Write-Host ""
            Write-Host "DOMAIN REMEDIATION INSTRUCTIONS:" -ForegroundColor Yellow
            Write-Host "================================" -ForegroundColor Yellow
            Write-Host "1. Open Group Policy Management Console (gpmc.msc)" -ForegroundColor White
            Write-Host "2. Navigate to: Default Domain Policy" -ForegroundColor White
            Write-Host "3. Edit: Computer Configuration\Policies\Windows Settings\Security Settings\Account Policies\Password Policy" -ForegroundColor White
            Write-Host "4. Set 'Store passwords using reversible encryption' to Disabled" -ForegroundColor White
            Write-Host "5. Apply the policy and run 'gpupdate /force' on all domain computers" -ForegroundColor White
            Write-Host ""
            Write-Host "Note: Domain policy changes require domain administrator privileges" -ForegroundColor Gray
        }
        
        $scriptResult = [PSCustomObject]@{
            Status = "ManualActionRequired"
            Message = "Domain environment requires manual policy changes"
            PreviousValue = "Unknown"
            NewValue = "Disabled"
            IsCompliant = $false
            RequiresManualAction = $true
            Source = "Domain Policy"
        }
    } else {
        if ($VerboseOutput) {
            Write-StatusMessage -Message "Standalone environment - applying local policy remediation" -Type Info
        }
        
        try {
            # Create a temporary security policy template
            $templateFile = [System.IO.Path]::GetTempFileName()
            $templateContent = @"
[Unicode]
Unicode=yes
[Version]
signature="`$CHICAGO`$"
Revision=1
[System Access]
ClearTextPassword=0
"@
            
            # Write the template
            $templateContent | Out-File -FilePath $templateFile -Encoding Unicode
            
            # Apply the security policy
            if ($VerboseOutput) {
                Write-StatusMessage -Message "Applying security policy template..." -Type Info
            }
            secedit /configure /db secedit.sdb /cfg $templateFile /quiet
            
            if ($LASTEXITCODE -eq 0) {
                if ($VerboseOutput) {
                    Write-StatusMessage -Message "Security policy applied successfully" -Type Success
                    Write-StatusMessage -Message "Verifying remediation..." -Type Info
                }
                Start-Sleep -Seconds 2
                
                $scriptResult = [PSCustomObject]@{
                    Status = "Remediated"
                    Message = "Store passwords using reversible encryption successfully disabled"
                    PreviousValue = "Unknown"
                    NewValue = "Disabled"
                    IsCompliant = $true
                    RequiresManualAction = $false
                    Source = "Local Policy"
                }
            } else {
                if ($VerboseOutput) {
                    Write-StatusMessage -Message "Failed to apply security policy (exit code: $LASTEXITCODE)" -Type Error
                    Write-Host ""
                    Write-Host "ALTERNATIVE REMEDIATION:" -ForegroundColor Yellow
                    Write-Host "========================" -ForegroundColor Yellow
                    Write-Host "1. Open Local Security Policy (secpol.msc)" -ForegroundColor White
                    Write-Host "2. Navigate to: Account Policies\Password Policy" -ForegroundColor White
                    Write-Host "3. Set 'Store passwords using reversible encryption' to Disabled" -ForegroundColor White
                    Write-Host "4. Click Apply and OK" -ForegroundColor White
                }
                
                $scriptResult = [PSCustomObject]@{
                    Status = "Failed"
                    Message = "Failed to apply security policy (exit code: $LASTEXITCODE)"
                    PreviousValue = "Unknown"
                    NewValue = "Disabled"
                    IsCompliant = $false
                    RequiresManualAction = $true
                    Source = "Local Policy"
                }
            }
            
            # Clean up temp file
            Remove-Item $templateFile -ErrorAction SilentlyContinue
            
        } catch {
            if ($VerboseOutput) {
                Write-StatusMessage -Message "Failed to remediate local policy: $($_.Exception.Message)" -Type Error
                Write-Host ""
                Write-Host "MANUAL REMEDIATION REQUIRED:" -ForegroundColor Red
                Write-Host "===========================" -ForegroundColor Red
                Write-Host "Please manually set the password policy:" -ForegroundColor White
                Write-Host "1. Open Local Security Policy (secpol.msc)" -ForegroundColor White
                Write-Host "2. Navigate to: Account Policies\Password Policy" -ForegroundColor White
                Write-Host "3. Set 'Store passwords using reversible encryption' to Disabled" -ForegroundColor White
                Write-Host "4. Click Apply and OK" -ForegroundColor White
            }
            
            $scriptResult = [PSCustomObject]@{
                Status = "Error"
                Message = "Failed to remediate local policy: $($_.Exception.Message)"
                PreviousValue = "Unknown"
                NewValue = "Disabled"
                IsCompliant = $false
                RequiresManualAction = $true
                Source = "Local Policy"
            }
        }
    }
    
    # Output result
    if ($scriptResult -eq $null) {
        $scriptResult = [PSCustomObject]@{
            Status = "Unknown"
            Message = "Script completed without setting a result"
            PreviousValue = $null
            NewValue = $null
            IsCompliant = $false
            RequiresManualAction = $false
            Source = "Unknown"
        }
    }
    
    # Return appropriate result based on verbose mode
    if ($VerboseOutput) {
        $scriptResult
    } else {
        $scriptResult.IsCompliant
    }
    
    if ($VerboseOutput) {
        Write-Host ""
        Show-Pause -Message "Press Enter to exit..."
    }
    
} catch {
    if ($VerboseOutput) {
        Wait-OnError -ErrorMessage "Failed to perform password policy remediation: $($_.Exception.Message)"
    } else {
        $false
    }
}